### ISSUE TITLE
ether => token at incentivPool and reservePool

### ISSUE THREAD

**Issue by JhChoy** [Strawberry-Pizza/ICO2.0#2]
@jw-pyo 
At function dividePoolAfterSale of Fund.sol
`
address(inc_pool).transfer(this.balance.mul(asset_percent[1]).div(100));
        address(res_pool).transfer(this.balance.mul(asset_percent[2]).div(100));`
this should be changed with transfer of ether => token.

**Comment by jw-pyo** [comment]
It would be fixed in next commit
